### ISSUE TITLE
[BUG] Metamask - Token Lost during pancake swap, it doesn't transfer to correct address somehow

### ISSUE THREAD

**Issue by shiningazure** [pancakeswap/pancake-frontend#1850] opened 2021-08-05 17:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use pancake swap using Metamask wallet and do a swap from BNB to PVU Token.
Steps : 
1. Open pancake swap and connect to metamask
2. Do the swap (0.7 BNB to 5PVU)
3. Confirm

Transaction id : https://bscscan.com/tx/0x4947fb08c69e163f3925884327125acee94e08708d3913b457e6fa1be25a1d79
![image](https://user-images.githubusercontent.com/18004349/128393323-5b2a81b4-fb9d-4760-b0cf-9087c1ab7e9b.png)

Somehow my BNB token reduced but my PVU Token didn't increase, so I checked the transaction, and found a pretty weird bug. The swap transaction should be ended and began with my Address, but instead, it goes to other address during swapping.

![image](https://user-images.githubusercontent.com/18004349/128393690-ca2566ac-69a9-4e59-b190-e3fd7424460d.png)

My wallet address : 0x376a419a62aef20ccada24eee452280035b79f4f

For further investigation, I search through bsc scan : https://bscscan.com/address/0x376A419a62aEF20cCAdA24EEe452280035B79F4F

I found that somehow the transaction was listed as OUT, but on the BEP-20 Token Txns, I didn't receive any PVU.

### Expected Behavior

Expected behaviour : 
PVU should be appeared on my account, but instead it didn't appear.

### Steps To Reproduce

1. Open pancake swap and connect to metamask
2. Do the swap (0.7 BNB to 5PVU)
3. Confirm

### Environment

```markdown
- Device: ROG GL552
- OS: Windows 10
- Browser: Chrome
- Wallet: Metamask - 0x376A419a62aEF20cCAdA24EEe452280035B79F4F
```

**Comment by Chef-Chungus** [comment] 2021-08-06 03:00
![image](https://user-images.githubusercontent.com/71833681/128449345-6c9a8bfb-b3e2-4b62-ae5e-c0dcffdb020f.png)
The PVU is in your wallet. I will be closing this as it's not a bug. 

You simply need to add the token to your wallet for it to display.

**Closed by Chef-Chungus** 2021-08-06 03:00 UTC
Labels: Bug

**Comment by shiningazure** [comment] 2021-08-06 03:05
1 PVU is from the swap i did on metamask swap, not the pancake swap. The pancake swap one is 5 PVU. 


Pancake swap transaction id : 
https://bscscan.com/tx/0x4947fb08c69e163f3925884327125acee94e08708d3913b457e6fa1be25a1d79

The transaction id of the metamask swap you mentioned is : https://bscscan.com/tx/0x428828d0079cc083ca9ce5356e8091a08b1d78f7d346825d1ab46a3790b11479

**Comment by Chef-Chungus** [comment] 2021-08-06 03:40
https://bscscan.com/address/0x13c7dd34da7734cc6beaf9b3edbe4e32a2dff7b9#tokentxns
If this address is not your own, I recommend checking to ensure you were visiting the correct URL for PancakeSwap and/or checking to make sure you don't have malware on your device.

If you were to use a malicious site, they can change the recipient address of the swap and receive the tokens into their wallet instead of your own.

This is definitely an instance of malicious activity or user error, unfortunately.
